### ISSUE TITLE
Please, add possibility to convert your model to ggml.

### ISSUE THREAD

**Issue by JohnClaw** [GreenBitAI/low_bit_llama#2]
I tried to convert your model to ggml and got this error:
C:\kcp>python convert.py ga7/
Loading model file ga7\pytorch_model.bin
Traceback (most recent call last):
  File "C:\kcp\convert.py", line 1325, in <module>
    main()
  File "C:\kcp\convert.py", line 1305, in main
    model_plus = load_some_model(args.model)
  File "C:\kcp\convert.py", line 1220, in load_some_model
    models_plus.append(lazy_load_file(path))
  File "C:\kcp\convert.py", line 1011, in lazy_load_file
    return lazy_load_torch_file(fp, path)
  File "C:\kcp\convert.py", line 882, in lazy_load_torch_file
    model = unpickler.load()
  File "C:\kcp\convert.py", line 871, in find_class
    return self.CLASSES[(module, name)]
KeyError: ('torch', 'ByteStorage')

**Comment by yanghaojin** [comment]
We will provide it soon.

**Comment by JohnClaw** [comment]
> We will provide it soon.

Thank you very much.
